/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
  }
}

// For TSX support
declare global {
  const ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElCollapse: typeof import('element-plus/es')['ElCollapse']
  const ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSplitter: typeof import('element-plus/es')['ElSplitter']
  const ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const ElTableV2: typeof import('element-plus/es')['ElTableV2']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
}